import { Inter, Philosopher, Crimson_Pro } from "next/font/google"
import "./globals.css"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
})

const philosopher = Philosopher({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-philosopher",
})

const crimsonPro = Crimson_Pro({
  subsets: ["latin"],
  variable: "--font-crimson-pro",
})

export const metadata = {
  title: "IKS Gyan Gunjan",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="/js/libs/jquery.min.js"></script>
        <script src="/js/libs/html2canvas.min.js"></script>
        <script src="/js/libs/three.min.js"></script>
        <script src="/js/libs/pdf.min.js"></script>
        <script src="/js/pdf.worker.js"></script>
        <script src="/js/dist/3dflipbook.js"></script>
        <link rel="stylesheet" href="/css/custom-flipbook.css" />
      </head>
      <body
        suppressHydrationWarning
        className={`${inter.variable} ${philosopher.variable} ${crimsonPro.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  )
}